# CI Config

stages:
  - build
  - test
  - deploy

# Build the static files
build_static:
  variables:
    NODE_ENV: "production"
  stage: build
  artifacts:
    name: "build_static_${CI_BUILD_REF}"
    expire_in: 1d
    paths:
      - build
  image: node:8.9.4
  script:
    - yarn install --production=false
    - yarn build

# Run test suite
test:
  stage: test
  image: node:8.9.4
  script:
    - npm install -g create-react-app
    - yarn install --production=false
    - npm test

# Deploy to Production (S3)
deploy_prod:
  stage: deploy
  image: node:8.9.4
  only:
    - master
  dependencies: 
    - build_static
  script:
    - npm install -g s3-deploy
    - s3-deploy './build/**' --cwd './build/' --region ${AWS_REGION} --bucket ${AWS_S3_BUCKET_NAME} --invalidate --deleteRemoved
